esphome:
  name: esphome-web-dfcb8c
  friendly_name: esphome-web-dfcb8c
#  includes:
#    - custom_components/msz_t200_device/msz_t200_device.h

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf
external_components:    
  - source:
      type: local
      path: custom_components
      
# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret old_house_ssid
  password: !secret old_house_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-Dfcb8C"
    password: !secret node_ap_passward

  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.1.115
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

web_server:
  local: true

captive_portal:

status_led:
  pin:
    number: GPIO2
    inverted: true

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings
  - platform: restart
    name: "esphome-web-dfcb8c Restart"
  - platform: safe_mode
    name: "esphome-web-dfcb8c Restart (Safe Mode)"
debug:
  update_interval: 5s

# Logger must be at least debug (default)
logger:
  level: debug

text_sensor:
- platform: version
  name: "ESPHome Version"
- platform: debug
  device:
    name: "Device Info"
  reset_reason:
    name: "Reset Reason"
- platform: wifi_info
  ip_address:
    name: ESP IP Address
    address_0:
      name: ESP IP Address 0
#    address_1:
#      name: ESP IP Address 1
#    address_2:
#      name: ESP IP Address 2
#    address_3:
#      name: ESP IP Address 3
#    address_4:
#      name: ESP IP Address 4
  ssid:
    name: ESP Connected SSID
  bssid:
    name: ESP Connected BSSID
  mac_address:
    name: ESP Mac Wifi Address
  scan_results:
    name: ESP Latest Scan Results
  dns_address:
    name: ESP DNS Address







spi:
- id: spi0
  clk_pin: GPIO11
  mosi_pin: GPIO12
  miso_pin: GPIO13

msz_t200_device:
  id: msz_t200_dev_1
  spi_id: "spi0"
  cs_pin: GPIO10
  irq_pin: GPIO1
  text_sensors: [name: "Status", name: "Statistics", name: "SpiStat"]
  unit_module_1.1: "input8"
  unit_module_1.2: "input8"
  unit_module_1.3: "output8"
  unit_module_1.4: "output8"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"

  - platform: uptime
    type: seconds
    name: Uptime Sensor

  - platform: msz_t200_sens2
    msz_t200_device: msz_t200_dev_1
    unit_id: 1
    module_id: 2
    bus_id: 1
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 3s
  - platform: msz_t200_dallas
    msz_t200_device: msz_t200_dev_1
    unit_id: 1
    module_id: 3
    bus_id: 1
    temperature:
      name: "Write OK"
    humidity:
      name: "Dallas Humidity test"
    update_interval: 3s
  - platform: msz_t200_dallas
    msz_t200_device: msz_t200_dev_1
    unit_id: 1
    module_id: 3
    bus_id: 2
    temperature:
      name: "Write Err"
    humidity:
      name: "Dallas Humidity test"
    update_interval: 3s

binary_sensor:
  - platform: gpio
    name: "T200 test Pin #1"
    pin:
      msz_t200_device: msz_t200_dev_1
      unit_id: 1
      module_id: 1
      channel_id: 1
      number: 100
      mode:
        input: true
        pullup: true
      inverted: false
  - platform: gpio
    name: "T200 test Pin #2"
    pin:
      msz_t200_device: msz_t200_dev_1
      unit_id: 1
      module_id: 1
      channel_id: 2
      number: 2
      # One of INPUT or INPUT_PULLUP
      mode:
        input: true
        pullup: true
      inverted: false

switch:
  - platform: gpio
    name: "Living Room Dehumidifier"
    pin:
      msz_t200_device: msz_t200_dev_1
      unit_id: 1
      module_id: 1
      channel_id: 4
      number: 4
      mode:
        input: true
        pullup: true
      inverted: false

output:
  - id: light_output
    platform: gpio
    pin:
      msz_t200_device: msz_t200_dev_1
      unit_id: 1
      module_id: 3
      channel_id: 1
      number: 17
      mode:
        input: true
        pullup: true
      inverted: false
  - id: test_button
    platform: gpio
    pin:
      msz_t200_device: msz_t200_dev_1
      unit_id: 1
      module_id: 3
      channel_id: 2
      number: 18
      mode:
        input: true
        pullup: true
      inverted: false

#light:
#  - platform: fastled_clockless
#    chipset: WS2812
#    pin: GPIO18
#    num_leds: 1
#    rgb_order: GRB
#    name: "FastLED WS2811 Light"    
#  - platform: binary
#    name: "Desk Lamp"
#    output: light_output
